spring:
  datasource:
    url: jdbc:mysql://localhost:3306/contact_list_db
    password: root
    username: root
    hikari:
      maximum-pool-size: 4
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true